redmine_cms/config/routes.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap" => "cms_site#sitemap", :defaults => {:format => :xml}

match 'site/login', :to => 'cms_site#login', :as => 'cms_login', :via => [:get, :post]
match 'site/logout', :to => 'cms_site#logout', :as => 'cms_logout', :via => [:get, :post]
match 'site/register', :to => 'cms_site#register', :via => [:get, :post], :as => 'cms_register'
match 'site/lost_password', :to => 'cms_site#lost_password', :via => [:get, :post], :as => 'cms_lost_password'
match 'site/activate', :to => 'cms_site#activate', :via => :get
match 'site/expire_cache', :to => 'cms_site#expire_cache', :via => :get, :as => 'site_expire_cache'
match 'auto_completes/cms_page_tags' => 'auto_completes#cms_page_tags', :via => :get, :as => 'auto_complete_cms_page_tags'

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"
get 'cms_menus/parent_menu_options' => 'cms_menus#parent_menu_options'

scope '/cms' do
  resources :cms_pages, :path => 'pages' do
    member do
     get :preview
     get :expire_cache
    end
    collection do
      get :search
    end
  end
  resources :cms_parts, :path => 'parts' do
    member do
     get :expire_cache
     get :preview
    end
  end
  resources :cms_snippets, :path => 'snippets' do
    member do
      get :preview
    end
  end
  resources :cms_variables, :path => 'variables'
  resources :cms_layouts, :path => 'layouts' do
    member do
      get :preview
    end
  end
  resources :cms_assets, :path => 'assets', :except => [:edit, :update, :show]
  resources :cms_redmine_layouts, :path => 'redmine_layouts'
  resources :cms_menus, :path => 'menus'
  resources :cms_redirects, :path => 'redirects'
  resources :cms_settings, :path => 'settings' do
    collection do
      get 'redmine_hooks'
      post 'save'
    end
  end
  get "/:object_type/:id/history" => "cms_history#history", :as => "cms_object_history"
  get "/:object_type/:id/diff" => "cms_history#diff", :as => "cms_object_diff"
  get "/:object_type/:id/annotate" => "cms_history#annotate", :as => "cms_object_annotate"
  get 'assets/:id/(:filename)', :to => 'cms_assets#show', :id => /\d+/, :filename => /.*/, :as => 'named_asset'
  get 'assets/download/:id/:filename', :to => 'cms_assets#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_asset'
  get 'assets/download/:id', :to => 'cms_assets#download', :id => /\d+/, :as => 'download_cms_asset'
  get 'assets/thumbnail/:id/:size/:filename', :to => 'cms_assets#thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+|\d+x\d+/, :as => 'cms_thumbnail'
  get 'assets/timelink/:id/:timestamp/:key/:filename', :to => 'cms_assets#timelink', :id => /\d+/, :filename => /.*/, :timestamp => /\d+/, :key => /([0-9a-f]{32})/, :as => 'cms_timelink'
  get 'assets/edit', :to => 'cms_assets#edit', :as => :cms_assets_edit
  post 'assets', :to => 'cms_assets#update', :as => :cms_assets_update

  # Export
  get 'exports/:object_type/:id(.:format)' => 'cms_exports#new', :as => :cms_export
  post 'exports/:object_type/:id' => 'cms_exports#create'
  get 'exports/website' => 'cms_exports#website', :as => :cms_export_website
  post 'exports/website' => 'cms_exports#website'

  # Import
  get 'imports/website' => 'cms_imports#website', :as => :cms_import_website
  post 'imports/website' => 'cms_imports#website'
  get 'imports/:object_type' => 'cms_imports#new', :as => :cms_import
  post 'imports/:object_type' => 'cms_imports#create'

  # Voting
  get 'vote/:id' => 'cms_votes#vote', :as => :cms_page_vote
  resources :cms_page_queries
end

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/
get 'pages/:page_id/parts/*name' => 'cms_parts#show', :as => "show_site_part"

get 'pages/*path' => 'cms_pages#show', :as => "show_site_page"

redmine_cms/app/models/cms_page_query.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsPageQuery < Query
  VISIBILITY_PRIVATE = 0
  VISIBILITY_ROLES   = 1
  VISIBILITY_PUBLIC  = 2

  self.queried_class = CmsPage
  self.available_columns = []

  def initialize(attributes = nil, *args)
    super attributes
    self.filters ||= {}
  end

  def initialize_available_filters
    add_available_filter('name', :type => :string, :name => l(:label_cms_name))
    add_available_filter('slug', :type => :string, :name => l(:label_cms_slug))
    add_available_filter('title', :type => :string, :name => l(:label_cms_title))
    add_available_filter('content', :type => :string, :name => l(:label_cms_content))
    add_available_filter('field_name', :type => :string, :name => l(:label_cms_page_field_name))
    add_available_filter('part_name', :type => :string, :name => l(:label_cms_page_part_name))
    add_available_filter('part_description', :type => :string, :name => l(:label_cms_page_part_description))
    add_available_filter('created_at', :type => :date_past, :name => l(:label_cms_created_at))
    add_available_filter('updated_at', :type => :date_past, :name => l(:label_cms_updated_at))
    add_available_filter('part_content', :type => :string, :name => l(:label_cms_page_part_content))

    status_values = [[l(:label_cms_status_locked), RedmineCms::STATUS_LOCKED.to_s], [l(:label_cms_status_active), RedmineCms::STATUS_ACTIVE.to_s]]
    add_available_filter('status_id', :type => :list_optional,
                                      :values => status_values,
                                      :name => l(:label_cms_status))

    visibility_values = [[l(:field_admin), ''], ['Public', 'public'], ['Logged', 'logged']] + Group.where(:type => 'Group').map { |g| [g.name, g.id.to_s] }
    add_available_filter('visibility', :type => :list_optional,
                                       :values => visibility_values,
                                       :name => l(:label_cms_visibility))

    layout_values = CmsLayout.order(:name).map { |l| [l.name, l.id.to_s] }
    add_available_filter('layout_id', :type => :list_optional,
                                      :values => layout_values,
                                      :name => l(:label_cms_layout))

    tags_values = CmsPage.tags_cloud.map { |l| [l.name, l.id.to_s] }
    add_available_filter('cms_page_tags', :type => :list_optional, :name => l(:label_cms_page_tags), :values => tags_values)
  end

  def self.visible(*args)
    user = args.shift || User.current
    scope = CmsPageQuery.all
    if user.admin?
      scope.where("#{table_name}.visibility <> ? OR #{table_name}.user_id = ?", VISIBILITY_PRIVATE, user.id)
    elsif user.memberships.any?
      scope.where("#{table_name}.visibility = ?" +
        " OR (#{table_name}.visibility = ? AND #{table_name}.id IN (" +
          "SELECT DISTINCT q.id FROM #{table_name} q" +
          " INNER JOIN #{table_name_prefix}queries_roles#{table_name_suffix} qr on qr.query_id = q.id" +
          " INNER JOIN #{MemberRole.table_name} mr ON mr.role_id = qr.role_id" +
          " INNER JOIN #{Member.table_name} m ON m.id = mr.member_id AND m.user_id = ?" +
          " WHERE q.project_id IS NULL OR q.project_id = m.project_id))" +
        " OR #{table_name}.user_id = ?",
        VISIBILITY_PUBLIC, VISIBILITY_ROLES, user.id, user.id)
    elsif user.logged?
      scope.where("#{table_name}.visibility = ? OR #{table_name}.user_id = ?", VISIBILITY_PUBLIC, user.id)
    else
      scope.where("#{table_name}.visibility = ?", VISIBILITY_PUBLIC)
    end
  end

  def visible?(user=User.current)
    return true if user.admin?
    case visibility
    when VISIBILITY_PUBLIC
      true
    when VISIBILITY_ROLES
      Member.where(:user_id => user.id).joins(:roles).where(:member_roles => { :role_id => roles.map(&:id) }).any?
    else
      user == self.user
    end
  end

  def objects_scope(options={})
    scope = CmsPage.order(:name)
    options[:search].split(' ').collect{ |search_string| scope = scope.live_search(search_string) } unless options[:search].blank?
    scope = scope.includes((query_includes + (options[:include] || [])).uniq).
      where(statement).
      where(options[:conditions])
    scope
  end

  def query_includes
    [:layout, :author, :fields, :parts]
  end

  def results_scope(options = {})
    objects_scope(options)
  rescue ::ActiveRecord::StatementInvalid => e
    raise StatementInvalid.new(e.message)
  end

  def sql_for_field_name_field(_field, operator, value)
    string_filter_builder(operator, value, 'name', CmsPageField)
  end

  def sql_for_part_name_field(_field, operator, value)
    string_filter_builder(operator, value, 'name', CmsPart)
  end

  def sql_for_part_description_field(_field, operator, value)
    string_filter_builder(operator, value, 'description', CmsPart)
  end

  def sql_for_part_content_field(_field, operator, value)
    string_filter_builder(operator, value, 'content', CmsPart)
  end

  def sql_for_cms_page_tags_field(_field, operator, value)
    sw = ['!', '!~', '!*'].include?(operator) ? 'NOT' : ''
    page_ids = RedmineCrm::Tagging.where(:taggable_type => CmsPage.name)
    page_ids = page_ids.where(:tag_id => value) unless ['*', '!*'].include?(operator)
    page_ids = page_ids.uniq.pluck(:taggable_id).push(0)

    "(#{CmsPage.table_name}.id #{sw} IN (#{page_ids.join(',')}))"
  end

  def string_filter_builder(operator, value, filter_attr, filter_class)
    sw = ['!', '!~', '!*'].include?(operator) ? 'NOT' : ''
    case operator
    when '=', '!'
      like_value = "LIKE '#{value.first.to_s.downcase}'"
    when '!*'
      like_value = "IS NOT NULL OR #{filter_class.table_name}.#{filter_attr} = ''"
    when '*'
      like_value = "IS NOT NULL OR #{filter_class.table_name}.#{filter_attr} <> ''"
    when '~', '!~'
      like_value = "LIKE '%#{self.class.connection.quote_string(value.first.to_s.downcase)}%'"
    end

    fields_select = "SELECT #{filter_class.table_name}.page_id FROM #{filter_class.table_name} WHERE LOWER(#{filter_class.table_name}.#{filter_attr}) #{like_value}"

    "(#{CmsPage.table_name}.id #{sw} IN (#{fields_select}))"
  end
end

redmine_cms/app/controllers/cms_page_queries_controller.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsPageQueriesController < ApplicationController
  before_filter :find_query, :except => [:new, :create, :index]

  helper :queries
  include QueriesHelper

  def index
    case params[:format]
    when 'xml', 'json'
      @offset, @limit = api_offset_and_limit
    else
      @limit = per_page_option
    end
    @query_count = CmsPageQuery.visible.count
    @query_pages = Paginator.new @query_count, @limit, params['page']
    @queries = CmsPageQuery.visible.
                    order("#{Query.table_name}.name").
                    limit(@limit).
                    offset(@offset).
                    all
    respond_to do |format|
      format.html
      format.api
    end
  end

  def new
    @query = CmsPageQuery.new
    @query.user = User.current
    @query.build_from_params(params)
    @query.visibility = PeopleQuery::VISIBILITY_PRIVATE unless User.current.admin?
  end

  def create
    @query = CmsPageQuery.new(params[:query])
    @query.user = User.current
    @query.build_from_params(params)
    @query.visibility = PeopleQuery::VISIBILITY_PRIVATE unless User.current.admin?

    if @query.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to url_for(:controller => 'cms_pages', :action => 'index', :query_id => @query.id)
    else
      render :action => 'new', :layout => !request.xhr?
    end
  end

  def edit
  end

  def update
    @query.attributes = params[:query]
    @query.build_from_params(params)
    @query.visibility = PeopleQuery::VISIBILITY_PRIVATE unless User.current.admin?

    if @query.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to url_for(:controller => 'cms_pages', :action => 'index', :query_id => @query.id)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @query.destroy
    redirect_to url_for(:controller => 'cms_page_queries', :action => 'index', :set_filter => 1)
  end

  private

  def find_query
    @query = CmsPageQuery.find(params[:id])
    render_403 unless @query.editable_by?(User.current)
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

redmine_cms/app/views/cms_page_queries/_filters.html.erb
<%= javascript_tag do %>
var operatorLabels = <%= raw_json Query.operators_labels %>;
var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
var availableFilters = <%= raw_json query.available_filters_as_json %>;
var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
var allProjects = <%= raw_json query.all_projects_values %>;
$(document).ready(function(){
  initFilters();
  <% query.filters.each do |field, options| %>
  addFilter("<%= field %>", <%= raw_json query.operator_for(field) %>, <%= raw_json query.values_for(field) %>);
  <% end %>
});
<% end %>

<table id="filters-table">
</table>

<div class="add-filter">
<%= label_tag('add_filter_select', l(:label_filter_add)) %>
<%= select_tag 'add_filter_select', filters_options_for_select(query), :name => nil %>
</div>

<%= hidden_field_tag 'f[]', '' %>
<% include_calendar_headers_tags %>

redmine_cms/app/views/cms_page_queries/_form.html.erb
<%= error_messages_for 'query' %>

<div class="box">
  <div class="tabular">

    <p><label for="query_name"><%=l(:field_name)%></label>
    <%= text_field 'query', 'name', :size => 80 %></p>

    <% if User.current.admin? || User.current.allowed_to?(:manage_public_queries, @query.project) %>
    <p><label><%=l(:field_visible)%></label>
      <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
      <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
      <label class="block"><%= radio_button 'query', 'visibility', Query::VISIBILITY_ROLES %> <%= l(:label_visibility_roles) %>:</label>
      <% Role.givable.sorted.each do |role| %>
        <label class="block role-visibility"><%= check_box_tag 'query[role_ids][]', role.id, @query.roles.include?(role), :id => nil %> <%= role.name %></label>
      <% end %>
      <%= hidden_field_tag 'query[role_ids][]', '' %>
    </p>
    <% end %>
  </div>

  <fieldset id="filters"><legend><%= l(:label_filter_plural) %></legend>
    <%= render :partial => 'queries/filters', :locals => {:query => query}%>
  </fieldset>

</div>

<%= javascript_tag do %>
$(document).ready(function(){
  $("input[name='query[visibility]']").change(function(){
    var roles_checked = $('#query_visibility_1').is(':checked');
    var private_checked = $('#query_visibility_0').is(':checked');
    $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !roles_checked);
    if (!private_checked) $("input.disable-unless-private").attr('checked', false);
    $("input.disable-unless-private").attr('disabled', !private_checked);
  }).trigger('change');
});
<% end %>

redmine_cms/app/views/cms_page_queries/edit.html.erb
<h2><%= l(:label_query) %></h2>

<%= form_tag(cms_page_query_path(@query), :method => :put) do %>
  <%= render :partial => 'form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>

redmine_cms/app/views/cms_page_queries/index.html.erb
<div class="contextual">
<%= link_to_if_authorized l(:label_query_new), {:controller => 'cms_page_queries', :action => 'new'}, :class => 'icon icon-add' %>
</div>

<h2><%= l(:label_query_plural) %></h2>

<% if @queries.empty? %>
  <p><i><%=l(:label_no_data)%></i></p>
<% else %>
  <table class="list">
  <% @queries.each do |query| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="name">
        <%= link_to query.name, :controller => 'cms_pages', :action => 'index', :query_id => query %>
      </td>
      <td class="buttons">
        <% if query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_cms_page_query_path(query), :class => 'icon icon-edit' %>
        <%= delete_link cms_page_query_path(query) %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>

redmine_cms/app/views/cms_page_queries/new.html.erb
<h2><%= l(:label_query_new) %></h2>

<%= form_tag(cms_page_queries_path) do %>
  <%= render :partial => 'form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>